######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 1 14:43:28 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS = musicsheet
# Directories
