######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 13 19:12:40 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += reporter processor monitor # destination
