######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 13 19:13:56 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS +=  localdb ibackup # email
