######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 10 11:53:12 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS = local # robocopy # cdrom virtual local rsync
