######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 13 19:15:14 2010
######################################################################

TEMPLATE = lib
CONFIG += plugin
INCLUDEPATH += ../
# Input
HEADERS += email.h
SOURCES += email.cpp
