######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 12 12:29:22 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += exe msi zip

