######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 19 19:43:47 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += local
