######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 2 17:36:13 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += diskspace
